import { Table } from "ts-sql-query/Table";
import { DBConnection } from ".";

export const tSkater = new (class TSkater extends Table<
  DBConnection,
  "TSkater"
> {
  id = this.autogeneratedPrimaryKey("id", "uuid");
  name = this.column("name", "string");
  email = this.column("email", "string");
  picture = this.optionalColumn("ubication_latitude", "string");
  email_verified = this.optionalColumn("ubication_longitude", "string");
  created_at = this.column("created_at", "localDateTime");
  updated_at = this.column("updated_at", "localDateTime");
  constructor() {
    super("skater"); // table name in the database
  }
})();

export const tSkaterConnection = new (class TSkaterConnection extends Table<
  DBConnection,
  "TSkaterConnection"
> {
  id = this.autogeneratedPrimaryKey("id", "uuid");
  skater_a = this.column("skater_a", "uuid");
  skater_b = this.column("skater_b", "uuid");
  requested_by = this.column("requested_by", "uuid");
  type = this.column("type", "string");
  approved = this.column("approved", "boolean");
  rejected = this.column("rejected", "boolean");
  email_verified = this.optionalColumn("ubication_longitude", "string");
  requested_at = this.column("requested_at", "localDateTime");
  approved_at = this.column("approved_at", "localDateTime");
  rejected_at = this.column("rejected_at", "localDateTime");
  constructor() {
    super("skater_connection"); // table name in the database
  }
})();
