import { Table } from "ts-sql-query/Table";
import { DbConnection } from ".";
import { extractColumnsFrom } from "ts-sql-query/extras/utils";
export const tSkater = new (class TSkater extends Table<
  DbConnection,
  "TSkater"
> {
  id = this.autogeneratedPrimaryKey("id", "uuid");
  name = this.column("name", "string");
  email = this.column("email", "string");
  picture = this.optionalColumn("picture", "string");
  email_verified = this.optionalColumn("email_verified", "boolean");
  created_at = this.column("created_at", "localDateTime");
  updated_at = this.column("updated_at", "localDateTime");
  auth0_sub = this.column("auth0_sub", "string");
  constructor() {
    super("skater"); // table name in the database
  }
})();

export const tSkaterCols = extractColumnsFrom(tSkater);

export const tSkaterConnection = new (class TSkaterConnection extends Table<
  DbConnection,
  "TSkaterConnection"
> {
  id = this.autogeneratedPrimaryKey("id", "uuid");
  skater_a = this.column("skater_a", "uuid");
  skater_b = this.column("skater_b", "uuid");
  requested_by = this.column("requested_by", "uuid");
  type = this.column("type", "string");
  approved = this.column("approved", "boolean");
  rejected = this.column("rejected", "boolean");
  requested_at = this.column("requested_at", "localDateTime");
  approved_at = this.optionalColumn("approved_at", "localDateTime");
  rejected_at = this.optionalColumn("rejected_at", "localDateTime");
  constructor() {
    super("skater_connection"); // table name in the database
  }
})();

export const tSkaterConnectionCols = extractColumnsFrom(tSkaterConnection);
