-- SELECT version();
-- CREATE skater TABLE
CREATE TABLE IF NOT EXISTS skater(
  id bigint generated by default as identity primary key,
  "name" varchar(32) not null unique check (length(name) >= 3),
  email varchar(256) not null unique,
  picture varchar(1024),
  email_verified boolean not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
);

-- INSERT skater
INSERT INTO skater(
	name, email, picture, email_verified)
	VALUES ('NAME', 'name@gmail.com', 'TEST', TRUE);